--DROP TABLE days CASCADE;
--DROP TABLE days_aud CASCADE;
--DROP TABLE revinfo CASCADE;
--DROP TABLE schedule CASCADE;
--DROP TABLE schedule_aud CASCADE;

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;